### PR TITLE
take a query param to render row(s) redundantly

### PR DESCRIPTION
**Pull request by picaq**
totally not DRY code
renders entire table or renders a single row based on a query param
untested and unrefined

### CODE REVIEW

**Review by ccarse — APPROVED** [review]

**Comment by ccarse** [comment]
"untested and unrefined" exactly how I like my code

**Comment by ccarse** [comment]
YOLO

**Comment by ccarse** [comment]
image
😭😭😭😭

**Comment by picaq** [comment]
It’s untested. My guess would be line 176 being the culprit.

**Pull request merged**
